version: "3.8"

services:

  vault-server:
    image: vault:1.7.3
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK

  db-test-spring:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: mySuperPassword1234!
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"